### ISSUE TITLE
Document Running Local Clowder

### ISSUE THREAD

**Issue by BenGalewsky** [re-mat/clowder-extractors#24]
# Problem
Developers need to run a local instance of clowder to develop and debug extractors

# Approach
The Clowder GitHub repo has general instructions for [running the Framework in Docker-compose](https://github.com/clowder-framework/clowder/tree/develop?tab=readme-ov-file#extractors) but it might be out of date and needs specifics for the RE-MAT extractors...

I got it running at one point, but didn't document it carefully.

You need a copy of the clowder project's [docker-compose.yml](https://github.com/clowder-framework/clowder/blob/develop/docker-compose.yml) along with an add-on yaml file specifying the extractors to launch.

Here's a docker-compose-remat-extractors.yaml I've used for testing in the past:
```yaml
version: '3.5'

# to use the extractors start with
# docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.extractors.yml up -d

services:
  # ----------------------------------------------------------------------
  # EXTRACTORS
  # ----------------------------------------------------------------------

  experiment-from-excel:
    image: ghcr.io/re-mat/parameter-extractor:latest
    restart: unless-stopped
    networks:
      - clowder
    depends_on:
      - rabbitmq
      - clowder
    environment:
      - RABBITMQ_URI=${RABBITMQ_URI:-amqp://guest:guest@rabbitmq/%2F}

#  parameters-from-txt:
#    image: ghcr.io/re-mat/parameter-extractor:parameter-extractor
#    restart: unless-stopped
#    networks:
#      - clowder
#    depends_on:
#      - rabbitmq
#      - clowder
#    environment:
#      - RABBITMQ_URI=${RABBITMQ_URI:-amqp://guest:guest@rabbitmq/%2F}

#  dsc-csv-stripper:
#    image: ghcr.io/re-mat/dsc-csv-stripper:stage
#    restart: unless-stopped
#    networks:
#      - clowder
#    depends_on:
#      - rabbitmq
#      - clowder
#    environment:
#      - RABBITMQ_URI=${RABBITMQ_URI:-amqp://guest:guest@rabbitmq/%2F}
```

The command line in the comments is out of date. Docker compose is now part of docker desktop command:
```bash
docker compose -f docker-compose.yml -f docker-compose.extractors.yml up -d
```

It's useful to stop and reload an extractor without restarting the whole stack. I wrote this little script to stop a named extractor container:
```bash
#!/usr/bin/env bash

echo "Stopping $1"
docker stop "$1"; docker rm "$1"; docker image prune -f
```
## Adding A User to Login
Here are [instructions on adding the initial user](https://github.com/clowder-framework/clowder/tree/develop?tab=readme-ov-file#initializing-clowder)

# Approach
I think it will be best if we save a copy of the docker-compose file along with the extractor config files and instructions in this clowder-extractors repo.
